spring:
  application:
    name: PokemonApp
  datasource:
    url: jdbc:mysql://localhost:3306/pokemon_party
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    ddl-auto: update